# Generated by Django 5.2.7 on 2025-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='target_question_count',
            field=models.IntegerField(default=10),
        ),
    ]
