# Generated by Django 5.2.7 on 2025-11-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewsession_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview.questionbank'),
            preserve_default=False,
        ),
    ]
