# Generated by Django 5.2.7 on 2025-11-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.questionbank'),
        ),
    ]
